# version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: user-app
        volumes:
            - .:/var/www/html:cached
            - /var/www/html/vendor # Exclude vendor folder from being mounted
        depends_on:
            - redis
        networks:
            - gpm-frontend
            - gpm-backend

    nginx:
        image: nginx:alpine
        container_name: user-nginx
        ports:
            - 8003:80 #default 80:80
        volumes:
            - .:/var/www/html:cached
            - /var/www/html/vendor # Exclude vendor folder from being mounted
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - gpm-frontend

    redis:
        image: redis:alpine
        container_name: user-redis
        networks:
            - gpm-backend

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: user-redis-admin
        environment:
            - REDIS_HOSTS=local:user-redis:6379
        ports:
            - "8383:8081"
        networks:
            - gpm-backend
    db:
        build:
            context: ./
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - 3306:3306
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - gpm-backend

networks:
    gpm-frontend:
        external: false
        driver: bridge
    gpm-backend:
        external: false
        driver: bridge

volumes:
    db-data:

